# Generated by Django 4.1.5 on 2023-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_room_price_per_day_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_persons',
            field=models.IntegerField(default=1),
        ),
    ]
