# Generated by Django 4.1.5 on 2023-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_total_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room', max_length=255, unique=True),
        ),
    ]
