# Generated by Django 4.1.5 on 2023-01-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_mail',
            new_name='customer_email',
        ),
    ]
