# Generated by Django 4.1.5 on 2023-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_customer_mail_reservation_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
