# Generated by Django 4.1.5 on 2023-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_id_reservation_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.AutoField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
