# Generated by Django 4.1.5 on 2023-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
