# Generated by Django 4.1.5 on 2023-01-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_reservation_id_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
